#!/bin/bash
# /etc/xray/add-trojan

user=$2
pass=$4
days=$6
exp=$(date -d "$days days" +"%Y-%m-%d")

sed -i "/#trojan$/a\### $user $exp\n},{\"password\": \"$pass\",\"email\": \"$user\"}" /etc/xray/config.json
echo "### $user $exp" >> /etc/trojan/.trojan.db

domain=$(cat /etc/xray/domain)
port=443
path="/trojan"

link="trojan://${pass}@${domain}:${port}?sni=${domain}&type=ws&security=tls&host=${domain}&path=${path}#${user}"
echo "$link"
systemctl restart xray