#!/bin/bash
# /etc/xray/add-vmess

user=$2
days=$4
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "$days days" +"%Y-%m-%d")

# Tambahkan user ke config.json
sed -i "/#vmess$/a\### $user $exp\n},{\"id\": \"$uuid\",\"alterId\": 0,\"email\": \"$user\"}" /etc/xray/config.json

# Simpan ke database manual (optional)
echo "### $user $exp" >> /etc/vmess/.vmess.db

# Buat config link
domain=$(cat /etc/xray/domain)
port=443
path="/vmess"
network="ws"
tls="tls"

config=$(echo -n "{
  \"v\": \"2\",
  \"ps\": \"$user\",
  \"add\": \"$domain\",
  \"port\": \"$port\",
  \"id\": \"$uuid\",
  \"aid\": \"0\",
  \"net\": \"$network\",
  \"type\": \"none\",
  \"host\": \"$domain\",
  \"path\": \"$path\",
  \"tls\": \"$tls\"
}" | base64 -w0)

echo "vmess://$config"
systemctl restart xray